### ISSUE TITLE
Makefile capability to clean Elasticsearch and Prometheus Data

### ISSUE THREAD

**Issue by excalq** [kuskoman/logstash-exporter#104]
`make clean-elasticsearch`:

The docker-compose stack will, over a few days, fill its available disk space with generated Logstash data. This could easily be done via Elasticsearch's API as a Makefile operation.

`make clean-prometheus`:

Another related enhancement is flushing existing metrics from Prometheus in the persistent dockerized volume. Again, this can be done via API (Prometheus). The admin API would need to be enabled however.

**Comment by excalq** [comment]
I can, though it might be later in the week.

**Comment by kuskoman** [comment]
@satk0 wanna address this one?
