### ISSUE TITLE
support for flow metrics 

### ISSUE THREAD

**Issue by sagi-shimoni** [kuskoman/logstash-exporter#118]
First I would like to thank you for this very valuable project.
Would you please consider to add support for exporting flow metrics as well ?
[https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#flow-stats](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#flow-stats)

**Comment by kuskoman** [comment]
@sagi-shimoni since it seemed to be pretty easy to implement i created a PR, could you take a look on it to see whether it solves your issue?

**Comment by kuskoman** [comment]
ah, just noticed i forgot
```
QueueBackpressure
WorkerConcurrency
```

will add it later on, as i have to return to work

**Comment by sagi-shimoni** [comment]
@kuskoman Wow thank you so much for the quick action !!  Really appreciate it !
 and yes `QueueBackpressure` is actually the metric I'm after :)

**Comment by sagi-shimoni** [comment]
> @sagi-shimoni take a look on the PR now, everything should be there

Wonderful !! thank you very much :)
When are you planning to release new version ?

**Comment by kuskoman** [comment]
I can make a release after I merge it, so in a few minutes actually

**Comment by kuskoman** [comment]
@sagi-shimoni https://github.com/kuskoman/logstash-exporter/releases/tag/v1.3.0

**Comment by sagi-shimoni** [comment]
> @sagi-shimoni https://github.com/kuskoman/logstash-exporter/releases/tag/v1.3.0

Much appreciated :+1:
