### ISSUE TITLE
linux/arm64 Images for Docker Hub

### ISSUE THREAD

**Issue by excalq** [kuskoman/logstash-exporter#136]
This is a proposal to publish linux/arm64 images to Docker Hub, along side the linux/amd64. These are most useful for AWS Graviton EC2 instances, and may be beneficial for Docker users on Apple Silicon hardware.

**Comment by excalq** [comment]
The `build-docker-multi` Makefile target should make this simple, but I have not yet used that in Github actions.

**Comment by kuskoman** [comment]
@excalq @arousseau-coveo this is solved in #173 and tag v1.5.1 already got pushed in arm version
