### ISSUE TITLE
`make test-coverage` command doesn't work on Ubuntu Firefox

### ISSUE THREAD

**Issue by satk0** [kuskoman/logstash-exporter#148]
I have a problem with displaying the coverage report. 
`go tool cover -html=coverage.out` command creates HTML file in a /tmp location that Firefox cannot find. See more why [here](https://superuser.com/questions/1748689/file-tmp-in-firefox-does-not-show-contents-of-tmp)

![Screenshot from 2023-07-04 18-58-11](https://github.com/kuskoman/logstash-exporter/assets/54475808/99b017f8-c293-4974-96ae-195029b3c5b8)
 
Specifying where the command creates HTML file and then running the default browser:

`go tool cover -html=coverage.out -o coverage.html`
`xdg-open ./coverage.html`

solves the issue.

**Comment by kuskoman** [comment]
This is the standard way of executing go coverage,the problem is likely related to the way that go/browser is installed and/or to filesystem limitations
