### ISSUE TITLE
Unable to see few metrics

### ISSUE THREAD

**Issue by mjetpurwalaextr** [kuskoman/logstash-exporter#155]
What could be the reason that I am not able to see these metrics for my instance?

logstash_stats_events_in
logstash_stats_events_out
and 
logstash_stats_process_cpu_load_average_1m/5m/15m

However, I am able to correctly see:
logstash_stats_pipeline_events_in
logstash_stats_pipeline_events_out

Any suggestions please?

**Comment by mperkhou** [comment]
I have a similar issue, missing many stats, including all the ones the OP listed. These are the only stats that are available. 

We are using logstash version 6.8.23 running on an Oracle Linux 7 server,  and scraping with docker image kuskoman/logstash-exporter v1.4.0  (554c05779eec)

> 

go_gc_duration_seconds{} | 1
-- | --
go_gc_duration_seconds_count{} | 1
go_gc_duration_seconds_sum{} | 1
go_goroutines{} | 1
go_info{} | 1
go_memstats_alloc_bytes{} | 1
go_memstats_alloc_bytes_total{} | 1
go_memstats_buck_hash_sys_bytes{} | 1
go_memstats_frees_total{} | 1
go_memstats_gc_sys_bytes{} | 1
go_memstats_heap_alloc_bytes{} | 1
go_memstats_heap_idle_bytes{} | 1
go_memstats_heap_inuse_bytes{} | 1
go_memstats_heap_objects{} | 1
go_memstats_heap_released_bytes{} | 1
go_memstats_heap_sys_bytes{} | 1
go_memstats_last_gc_time_seconds{} | 1
go_memstats_lookups_total{} | 1
go_memstats_mallocs_total{} | 1
go_memstats_mcache_inuse_bytes{} | 1
go_memstats_mcache_sys_bytes{} | 1
go_memstats_mspan_inuse_bytes{} | 1
go_memstats_mspan_sys_bytes{} | 1
go_memstats_next_gc_bytes{} | 1
go_memstats_other_sys_bytes{} | 1
go_memstats_stack_inuse_bytes{} | 1
go_memstats_stack_sys_bytes{} | 1
go_memstats_sys_bytes{} | 1
go_threads{} | 1
logstash_exporter_build_info{} | 1
logstash_info_up{} | 1
process_cpu_seconds_total{} | 1
process_max_fds{} | 1
process_open_fds{} | 1
process_resident_memory_bytes{} | 1
process_start_time_seconds{} | 1
process_virtual_memory_bytes{} | 1
process_virtual_memory_max_bytes{} | 1
promhttp_metric_handler_requests_in_flight{} | 1
promhttp_metric_handler_requests_total{}

`

**Comment by kuskoman** [comment]
I created #157 in order to debug it easier.
After my debug I saw that  logstash `8.8.1` has different metrics exposed and different document structure than `6.8.23` mentioned by linux.
Since it is my side project I don't plan spending time creating connectors for multiple logstash versions, however some time ago I created https://github.com/kuskoman/logstash-metric-samples, so in the future it is possible that I will provide a compatibility table in the readme.

In order to utilize all avaiable metrics you need to upgrade your logstash to current (8.8.x) version

**Comment by kuskoman** [comment]
I'm testing SweepAI to see whether its captable of generating the compatibility table
#160 #158 
Not sure if it will actually fit our needs, but I want to have some fun with it

**Comment by kuskoman** [comment]
I updated readme ( https://github.com/kuskoman/logstash-exporter/commit/38acc6174b0fe50f4bf7eaa2703f07fa981cdf16 ) to add information about supported logstash version
