### ISSUE TITLE
Helm chart:  template to be used as a side car for this exporter when installing logstash chart from bitnami

### ISSUE THREAD

**Issue by pawellegowski89** [kuskoman/logstash-exporter#17]
Hi,

I like that finally someone decided to create a current project of a dedicated exporter for logstash metrics in a prometheus-accepted format.

I will try to help and post ready fragments of the values ​​file configuration that will allow you to implement this exporter as a side car together with the installation of the official helm chart from bitnami, which is used to install logstash. In addition, I will add a template that allows you to create a ServiceMonitor if Prometheus has been implemented as an operator. This will ensure that the target registers itself automatically.

I hope this will be helpful in creating a dedicated helm chart for this exporter.
Because there may also be a need to implement it separately, and not together with logstash (version from bitnami).

Regards
Paul

**Comment by kuskoman** [comment]
@pawellegowski89 I started working on a helm chart in style similar to this chart: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/, but feel free to provide any information that may help users to implement logstash exporter as a sidecar for their deployment, as this is not currently my main goal

**Comment by excalq** [comment]
It'd be great to have this generalized to work with any Logstash deployment. (We use a customized one with a JSON-reponse version of `logstash-http-input` and OpenSearch output plugins.) Happy to collaborate where possible as well.

**Comment by kuskoman** [comment]
@excalq does the approach presented in #66 match your requirements? if not, what changes are required for you to have the chart working properly?
the PR is in an early stage and since I am working on it in free time I cannot promise any deadline for it, but I apperciate any feedback.

**Comment by excalq** [comment]
That chart looks great, and I'll test it out this week, and give feedback. I hadn't seen the draft PR, but great to see it now - thanks for the link.

**Comment by excalq** [comment]
Fixes to the chart are posted in PR #74 😀 Next I'd like to get it to export metrics for multiple Logstash replicas, each with their own labels. I'm thinking about what the configuration might look like. Perhaps fetching annotations rather than a static `url` set in `values.yaml`.
