### ISSUE TITLE
Add Support for Version Command

### ISSUE THREAD

**Issue by iveelsm** [kuskoman/logstash-exporter#187]
It would be nice to be able to validate the version of the binary without having to start the service completely. There are a few reasons why you would want to do this, but one example is when using salt states for managing deployments. I have a salt state set up for this project, and would love to have a simple version check to determine if any upgrades need to happen.

This request could likely be expanded beyond just a version command into multiple different command line arguments. The expected output of the request might resemble something like the following:

```
$ logstash-exporter -v
v1.5.4
```

**Comment by iveelsm** [comment]
As an additional note here, I am happy to tackle this on my own. Just making sure to follow the guidelines and see if this would be a valuable change before marching forward.

**Comment by kuskoman** [comment]
Hello
I appercicate creating the issue
Feel free to start working on it, however please note, that I pretty recently created the 'v2' branch, so you may consider making PR to it. The branch v2 is focused on braking changes that would allow yaml configuration and exporting multiple instances, so it is not related, but it may be just less work to create PR there than to rebase it from v1 later. This is not neccessary, so if you want to target the current master, feel free to go for it
