### ISSUE TITLE
Dockerfile using binary file

### ISSUE THREAD

**Issue by kksaha** [kuskoman/logstash-exporter#207]
Trying to create an image using this Dockerfile, but doesn't seems to valid.

`FROM xyz/debian:bullseye-slim

ARG APP_VERSION="v1.5.6"
ARG APP_USER="logstash"
ARG APP_UID="1000"
ARG APP_GROUP="${APP_USER}"
ARG APP_GID="${APP_UID}"

ARG APP_DIR="/app"

ENV PATH="${APP_DIR}/bin:${PATH}"

SHELL ["/bin/bash", "-c"]

RUN groupadd --gid "${APP_GID}" "${APP_GROUP}" && \
    useradd --uid "${APP_UID}" --gid "${APP_GID}" --home "${APP_DIR}" "${APP_USER}"

RUN apt-get update && \
    apt-get install bzip2 wget -y

WORKDIR /tmp

RUN wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux" && \
    wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux.sha256" && \
    sha256sum -c logstash-exporter-linux.sha256

WORKDIR "${APP_DIR}"

COPY . "${APP_DIR}"

RUN chown --recursive "${APP_USER}":"${APP_GROUP}" "${APP_DIR}"

USER "${APP_USER}"

ENTRYPOINT ["/app/main"]`

Could you please the share the Dockerfile to create an image using binary.

**Comment by kuskoman** [comment]
Hello @kksaha 
the problem is not related to my application and the problem exists only because of invalid dockerfile, but since it was pretty easy to fix i found the solution

```dockerfile
FROM debian:bullseye-slim

ARG APP_VERSION="v1.5.6"
ARG APP_USER="logstash"
ARG APP_UID="1001"
ARG APP_GROUP="${APP_USER}"
ARG APP_GID="${APP_UID}"

ARG APP_DIR="/app"

ENV PATH="${APP_DIR}/bin:${PATH}"

SHELL ["/bin/bash", "-c"]

RUN groupadd --gid "${APP_GID}" "${APP_GROUP}" && \
    useradd --uid "${APP_UID}" --gid "${APP_GID}" --home "${APP_DIR}" "${APP_USER}"

RUN apt-get update && \
    apt-get install bzip2 wget -y

WORKDIR /tmp

RUN wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux" && \
    wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux.sha256" && \
    sha256sum -c logstash-exporter-linux.sha256 && \
    mkdir -p "${APP_DIR}" && \
    mv logstash-exporter-linux "${APP_DIR}/main" && \
    chmod +x "${APP_DIR}/main"

WORKDIR "${APP_DIR}"

COPY . "${APP_DIR}"

RUN chown --recursive "${APP_USER}":"${APP_GROUP}" "${APP_DIR}"

USER "${APP_USER}"

ENTRYPOINT ["/app/main"]
```

basically you should modify one of the run steps:
```dockerfile
RUN wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux" && \
    wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux.sha256" && \
    sha256sum -c logstash-exporter-linux.sha256 && \
    mkdir -p "${APP_DIR}" && \
    mv logstash-exporter-linux "${APP_DIR}/main" && \
    chmod +x "${APP_DIR}/main"
```

**Comment by kksaha** [comment]
Thanks for your promt response. However I have done almost similar and it was working.


`FROM debian:bullseye-slim

ARG APP_VERSION="v1.5.6"
ARG APP_USER="logstash"
ARG APP_UID="1000"
ARG APP_GROUP="${APP_USER}"
ARG APP_GID="${APP_UID}"
ARG APP_DIR="/app"

ENV PATH="${APP_DIR}/bin:${PATH}"

SHELL ["/bin/bash", "-c"]

RUN groupadd --gid "${APP_GID}" "${APP_GROUP}" && \
    useradd --uid "${APP_UID}" --gid "${APP_GID}" --home "${APP_DIR}" "${APP_USER}"

RUN apt-get update && \
    apt-get install bzip2 wget -y

WORKDIR /tmp

RUN wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux" && \
    wget "https://github.com/kuskoman/logstash-exporter/releases/download/${APP_VERSION}/logstash-exporter-linux.sha256" && \
    sha256sum -c logstash-exporter-linux.sha256

COPY logstash-exporter-linux /app/logstash-exporter

WORKDIR "${APP_DIR}"

RUN chmod +x /app/logstash-exporter
RUN chown --recursive "${APP_USER}":"${APP_GROUP}" "${APP_DIR}"

EXPOSE 9198

USER "${APP_USER}"

CMD ["./logstash-exporter"]`
