### ISSUE TITLE
arm64 stru is not support ? which format can download 

### ISSUE THREAD

**Issue by chengzi-xs** [kuskoman/logstash-exporter#211]

**Comment by kuskoman** [comment]
@chengzi-xs I can add arm64 version to artifacts. right now only docker image for this platform is available

**Comment by kuskoman** [comment]
for now you can clone the project and compile it yourself

**Comment by kuskoman** [comment]
You should be able to download ARM version: https://github.com/kuskoman/logstash-exporter/releases/tag/v1.5.7
