### ISSUE TITLE
[BUG] cannot unmarshal number 47244640256 into Go struct

### ISSUE THREAD

**Issue by waqarsky** [kuskoman/logstash-exporter#216]
Ive just downloaded v1.5.7 and run this exporter on my logstash machine (no config set up). 

I got this error on a logstash 7.17.5 instance: 

```time=2024-01-10T17:01:15.524Z level=ERROR msg="executor failed" name=nodestats duration=13.507973ms err="json: cannot unmarshal number 47244640256 into Go struct field .pipelines.queue.max_queue_size_in_bytes of type int"```

**Comment by kuskoman** [comment]
Fixed in both v1 and v2 versions.
For v1 (see tag [v1.6.0](https://github.com/kuskoman/logstash-exporter/releases/tag/v1.6.0))

**Comment by kuskoman** [comment]
@waqarsky fixed in both v1 and v2 versions.
For v1 see tag [v1.6.0](https://github.com/kuskoman/logstash-exporter/releases/tag/v1.6.0)
