### ISSUE TITLE
Find a way for reload timestamps to appear in README generated by script

### ISSUE THREAD

**Issue by kuskoman** [kuskoman/logstash-exporter#295]
There are two metrics:
```
| logstash_stats_pipeline_reloads_last_failure_timestamp | gauge | Timestamp of last failed pipeline reload. |
| logstash_stats_pipeline_reloads_last_success_timestamp | gauge | Timestamp of last successful pipeline reload. |
```
That only appear after at least one pipeline is reloaded. Currently doing it involves manual process.
https://discuss.elastic.co/t/restart-individual-logstash-pipeline/168100
Would be nice to modify ./scripts/add_metrics_to_readme.sh, so that it will do it automatically
Also, the script seems to be missing set -euo pipefail

**Comment by satk0** [comment]
Shouldn't we close this issue? @kuskoman
