### ISSUE TITLE
Exporter fails to unmarshal heap information

### ISSUE THREAD

**Issue by luisfelipegarcia** [kuskoman/logstash-exporter#300]
Running v1.6.2
Logstash 8.12.0
Ubuntu 22.04

Similar to issue https://github.com/kuskoman/logstash-exporter/issues/216

Getting the following error:

time=2024-02-27T17:27:45.329Z level=ERROR msg="executor failed" name=nodestats duration=196.621257ms err="json: cannot unmarshal number 17179869184 into Go struct field .jvm.mem.heap_committed_in_bytes of type int"

**Comment by kuskoman** [comment]
I fixed it for multiple memory-related fields. I probably will go through all metrics in v1 and v2 and try to find ones that can probably be easily overflown

**Comment by kuskoman** [comment]
Fixed in v1.6.3 https://github.com/kuskoman/logstash-exporter/releases/tag/v1.6.3
cc: @luisfelipegarcia
