### ISSUE TITLE
-config flag not defined

### ISSUE THREAD

**Issue by rolatsch** [kuskoman/logstash-exporter#335]
### Description of the Issue

Hey there,
i tried to use the `-config` flag to load a configuration but all i get is
```
$ /usr/local/bin/logstash-exporter-linux -config /etc/logstash_exporter/config.yml
flag provided but not defined: -config
Usage of /usr/local/bin/logstash-exporter-linux:
  -version
    	prints the version and exits
$ /usr/local/bin/logstash-exporter-linux -version
v1.6.4
```

### Version of logstash-exporter, or logstash-exporter Image

v1.6.4

### Operating System/Environment

Ubuntu 22.04

**Comment by kuskoman** [comment]
hello
the master branch has documentation for v2. to use v1 you need to switch to v1 branch and read readme file from there

**Comment by rolatsch** [comment]
ohh my bad.
Thank you.
