### ISSUE TITLE
HTTPS support for endpoints

### ISSUE THREAD

**Issue by genji333** [kuskoman/logstash-exporter#348]
### Feature Description

Hi! Is it possible to expose the endpoints in https instead of http? For instance: https://host-name/metrics

I might be missing something, but I can't find this in the documentation. 

### Version of logstash-exporter this feature request applies to

Both v1 and v2 (master)

**Comment by kuskoman** [comment]
@genji333 Hello
this is not something that i am planning to add to the application itself, however it feels like you are looking for SSL termination.
for k8s it is something that you can do using ingress
for barebone instances it can be done via reverse proxy, such as nginx

if you provide me some context on how are you using the exporter i may be able to suggest you a solution for that
