### ISSUE TITLE
Customized configuration isn't affected

### ISSUE THREAD

**Issue by yo-ga** [kuskoman/logstash-exporter#351]
### Description of the Issue

After create the configuration, it doesn't affected. All values of the configuration are still as same as default.

example config
```yaml
logstash:
  servers:
    - url: "http://logstash:9600"
server:
  port: 9196
logging:
  level: "debug"
```

### Version of logstash-exporter, or logstash-exporter Image

v1.6.4

### Logs

```sh
2024/08/16 16:42:52 open .env: no such file or directory
time=2024-08-16T16:42:52.155+08:00 level=INFO msg="Version: refs/tags/v1.6.4, SemanticVersion: v1.6.4, GitCommit: 96fad72419e8b5b76d3f6cfc7b958ca4a59c9c4a, GoVersion: go1.22.2, BuildArch: amd64, BuildOS: darwin, BuildDate: 2024-04-18T11:58:19UTC"
time=2024-08-16T16:42:52.160+08:00 level=INFO msg="starting server on" host="" port=9198
```

**Comment by satk0** [comment]
To use yaml config you need to use logstash v2, check out [v2.0.0-pre8 release](https://github.com/kuskoman/logstash-exporter/releases/tag/v2.0.0-pre8)
