### ISSUE TITLE
Flow _lifetime metrics are actually gauges

### ISSUE THREAD

**Issue by VCCPlindsten** [kuskoman/logstash-exporter#366]
### Description of the Issue

The flow metrics exposed by logstash API are in fact gauges, that is, average over the timeframe described (current being 10s). Upstream doc: https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#flow-stats

This may have been different in previous logstash versions?

logstash-exporter lists the following _lifetime metrics as counters, but the values behave like gauges (In logstash 8.15)
* logstash_stats_flow_filter_lifetime
* logstash_stats_flow_input_lifetime
* logstash_stats_flow_output_lifetime
* logstash_stats_flow_queue_backpressure_lifetime
* logstash_stats_flow_worker_concurrency_lifetime
* logstash_stats_pipeline_flow_filter_lifetime
* logstash_stats_pipeline_flow_input_lifetime
* logstash_stats_pipeline_flow_output_lifetime
* logstash_stats_pipeline_flow_queue_backpressure_lifetime
* logstash_stats_pipeline_flow_worker_concurrency_lifetime

In addition to changing the type, the help text should probably also be changed to indicate that this is the rate over the lifetime, rather than a total

### Version of logstash-exporter, or logstash-exporter Image

1.7.1

### Operating System/Environment

Logstash 8.15.0

**Comment by kuskoman** [comment]
Fixed for v1
@satk0 could you make a fix for v2?

**Comment by satk0** [comment]
yup

**Comment by satk0** [comment]
@kuskoman Done

**Comment by VCCPlindsten** [comment]
Suggestion for updating node-level metric types: #374
Pipelines was addressed by @satk0

**Comment by satk0** [comment]
Yea, if you find any other issue with exporter report it here, you are really helpful !
