### ISSUE TITLE
Sample Grafana Dashboard?

### ISSUE THREAD

**Issue by excalq** [kuskoman/logstash-exporter#75]
I'm currently testing the metrics I've generated from PR #74, though I noticed the other Grafana dashboard [examples](https://grafana.com/grafana/dashboards/2525-logstash/) in [existence](https://github.com/dpavlos/logstash-monitoring) don't use the same metric names and labels. 

Do you have a Grafana dashboard (JSON export) that has these metrics? If not, I'll create one and share it, but figured it's worth asking if it same some duplicated effort.

---

_UPDATE: The published Grafana.com Dashboard URL: https://grafana.com/grafana/dashboards/18628-logstash-on-kubernetes-dashboard/_

**Comment by excalq** [comment]
No worries, we're doing a stress test of a new stack this week, so I'll build one and share it. I may PR some changes to the Go code with additional metrics as well.

**Comment by excalq** [comment]
Here's the Grafana Dashboard for this project! Requires v1.0.3+

https://grafana.com/grafana/dashboards/18628-logstash-monitoring-aws-dev/

**Comment by kuskoman** [comment]
@excalq ![image](https://user-images.githubusercontent.com/15456923/235062829-24d1cd91-263d-48a0-b3d0-8742d2ddc056.png) i am getting 404

**Comment by excalq** [comment]
Try again - I assumed they do content moderation before releasing it publicly.

**Comment by kuskoman** [comment]
@excalq I will create a PR to README.md file with a link to this dashboard and close this issue after merging it

**Comment by jhill-cmd** [comment]
just saw. any link ?

**Comment by jhill-cmd** [comment]
"Using on non-Kubernetes deployments? Just change the label and filter pod to instance"
![image](https://github.com/kuskoman/logstash-exporter/assets/1371103/cb0a5abd-b9b2-4d0b-b5b7-2ae8cabb19ec)
Is it normal the $pod is [object] ?
