### ISSUE TITLE
Allow to specify multiple logstash instances

### ISSUE THREAD

**Issue by kuskoman** [kuskoman/logstash-exporter#79]
Right now only one host can be specified for the exported to be scrapped. This disallows using a single exporter for multiple logstash instances.
To properly implement this feature I need to:
- [ ] add labels that will allow applications consuming prometheus data distinguish between different instances
- [ ] allow to specify multiple logstash hosts, instead of a single one

**Comment by kuskoman** [comment]
@excalq regarding #78- since I am not a big fan of the idea of packing the whole kubernetes api to the applicaiton, I would like to provide a different method to configure the app for service discovery. This way it could be done for example by init container that would contain a script that does service discovery and passes env file to the final container, or some custom kubernetes controller.

Also, if none of these solutions are sufficient, feel free to use this project as a library and create own cmd file, that would contain the kubernetes api client that you need.

**Comment by kuskoman** [comment]
@excalq personally I would approach it by creating a custom controller (possibly using https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that would watch pods with given custom annotation and restart the exporter pod after changes. This way you can avoid forking the repository and separate concerns.

You can also approach the problem the way that you already did. in this case I would recommend spinning your own repository and treating this repo as a library. your repository does not have to be a fork- you can just import all components except `main` package and provide own logic of service discovery. I am happy to help both answering questions and working on code for this solution. as i said, i would like to keep this application be dedicated to a single problem, but i want to treat it as both CLI and a library, so eventually I will try to come up with some structured public api for the app (i may restructure files for 2.x.x)

Another approach is to treat it as a sidecar- in my case there is a single exporter for each of logstash instances. this is one of the reasons why i want to keep it as small and simple as possible- spinning up that small container/process does not affect resource usage that much.

For 2 of these ideas you may need possibility to configure exporter for multiple hosts- it is a feature i will work on soon (i wanted to link #79 then realised we are already talking in this issue :D)

**Comment by kuskoman** [comment]
@excalq moving the conversation from #78:

> Avoids maintenance of custom changes to Elastic's Logstash helm chart

this is basically my first idea, you can make a single change/add a single value to the chart: annotation for a pod, then look for pods with given annotations and either inject a sidecar, spawn another exporter pod, or adjust configuration

**Comment by excalq** [comment]
Thanks @kuskoman for this analysis of various approaches. Keeping this small and free of Kubernetes client bloat makes sense, as it may very well be ran on bare-metal, in Docker-Compose, etc. Using it as a sidecar also makes sense, and should be doable with the existing Elastic or Bitnami Logstash Helm charts. 

As far as custom controllers, I'm interested in trying something out (as a separate project), as it'd be an interesting learning opportunity, and a useful OSS contribution. Of course, a mechanism to register (or even update) multiple host endpoints would be useful.

**Comment by pjaak** [comment]
Hi @kuskoman ,

I was wondering is this still being looked at?

Thanks

**Comment by kuskoman** [comment]
Hello @pjaak 
this is somehting that I plan to do, but I cannot specify time window when I will be able to work on it.
However, PRs for the feature are welcome
