### ISSUE TITLE
Add Boolean Metric for Instantaneous Pipeline Health

### ISSUE THREAD

**Issue by excalq** [kuskoman/logstash-exporter#93]
Currently (as far as I can tell) there is no mechanism to directly verify that a pipeline is healthy at a single instance in time. Metrics such as `logstash_stats_pipeline_events_out` can show a timeseries drop-off, but I'd like to have a boolean `_up` or `_healthy` metric for each pipeline (as a label). This is an issue for a PR I'll create for this.

### Proposed mechanism
Logstash does not directly produce such a metric, however it does emit `pipelines.[pipeline_id].reloads.last_success_timestamp` and `pipelines.[pipeline_id].reloads.last_failure_timestamp`. 

1. If both are `null`, the pipeline is considered **working**.
2. If `last_failure_timestamp` has a value, but `last_success_timestamp` is `null`, the pipeline is **broken**, and has been since the service started.
3. If `last_failure_timestamp > last_success_timestamp`, the pipeline is **broken**.
4. If `last_success_timestamp > last_failure_timestamp`, the pipeline is now **working**.

In my testing, of hot-reloading with a simple invalid pipeline syntax: `output: "**** INTENTIONAL BROKEN CONFIGMAP ****" `, the above works as described on Logstash 8.4.0. If there are considerations or scenarios this doesn't work for, please advise.

### Proposed name
`logstash_stats_pipeline_up{pipeline_id="$pipeline"}`, following the existing nomenclature of `logstash_info_up`. Any better suggestion is welcome.

### Version Compatibility

These metrics were introduced in Logstash 5.0.0: https://github.com/elastic/logstash/pull/5848

### Screenshots of the above scenarios:

1. Pipeline is *working*
<img width="961" alt="image" src="https://user-images.githubusercontent.com/610274/233439598-e541a2a5-77e7-481d-aba8-b93a0906aab3.png">

2. Pipeline is *broken*, started broken
<img width="961" alt="image" src="https://user-images.githubusercontent.com/610274/233440067-4092f03e-e989-4954-bc20-1246a9edbb71.png">

3. Pipeline is *broken*, started healthy (hot reload)
<img width="961" alt="image" src="https://user-images.githubusercontent.com/610274/233440276-fd1897cf-63c8-4485-b619-7c927c296982.png">

4. Pipeline is *working*, fixed from broken state (hot reload)
<img width="961" alt="image" src="https://user-images.githubusercontent.com/610274/233440369-15cb46a0-c7ad-4d8b-a704-8f967843daa6.png">

**Comment by kuskoman** [comment]
@excalq how about these two metrics? https://github.com/kuskoman/logstash-exporter/blob/f95c9e3b09c4e8ac6deab894f0b5d4cc2b97990e/collectors/nodeinfo/nodeinfo_collector.go#L22 and https://github.com/kuskoman/logstash-exporter/blob/f95c9e3b09c4e8ac6deab894f0b5d4cc2b97990e/collectors/nodeinfo/nodeinfo_collector.go#L28

**Comment by kuskoman** [comment]
Ah, I just realised it is different metric

So, it is possible that the pipeline will be down, but the instance will be up, right?

**Comment by excalq** [comment]
Yes, that's the idea, the instance is running fine, and even other pipelines are running, but one may be in an error state. This is what the new metric `logstash_stats_pipeline_up` can produce in Grafana:

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/610274/233680968-0a5d61ee-138a-4baa-bf37-3d45f65c1da3.png">

**Comment by kuskoman** [comment]
@excalq I want to merge it, but since it is not so obvious I will create documentation for it, as well as cover more test cases
